language: go

go:
 - 1.8.x
 - 1.9

before_install:
 - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libx11-dev

sudo: required
dist: trusty

install:
  - go get -t ./...
  - go get github.com/golang/lint/golint
  # Install gometalinter
  - go get github.com/alecthomas/gometalinter

script:
 - go test -race -v ./tapdance/
 - go test -race -v ./tdproxy/
 - gometalinter --install
 - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E deadcode --tests ./tapdance/
